root: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
env:
  browser: false
  es2021: true
  node: true
extends:
  - standard
  - eslint:recommended
  - prettier
plugins:
  - import
  - jsdoc
  - prettier

rules:
  prettier/prettier: error

  no-underscore-dangle: error

  max-nested-callbacks:
    - error
    - max: 4
  max-statements-per-line:
    - error
    - max: 1
  no-console: error
  no-empty-function: error
  no-inline-comments: error
  no-lonely-if: error
  no-shadow: off
  no-plusplus: off
  no-var: error
  no-implicit-coercion:
    - error
    - boolean: true
      number: true
  prefer-const: error
  semi:
    - error
    - never

  import/no-unresolved: error
  import/prefer-default-export: 'off'
  import/no-deprecated: error
  import/named: error
  import/namespace: error
  import/default: error
  import/export: error
  import/extensions: off
  import/order:
    - error
    - newlines-between: always
      warnOnUnassignedImports: true
      groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      alphabetize:
        order: asc
